debug: False

locale:
  tz: Europe/Vienna

security:
  min_pw_len: 8
  algorithm: HS256
  expire_minutes: 3600
  allow_rfid_login: true

server:
  host: 0.0.0.0
  port: 5000
  domain: "glados.local"
  api:
    web: "/api/web/v1"
    pat: "/api/pat/v1"
    key: "/api/key/v1"
  static:
    enable: false
    folder: "/path/to/static"
    url: "/"
  ssl:
    keyfile: "/path/to/keyfile.key"
    certfile: "/path/to/certfile.crt"
  headers_server: true
  headers_proxy: true
  forwarded_allowed_ips: null

schedules:
  database_hour: 0
  system_hour: 0
  email_notifications_hour: 6
  backup_db_hour: 0
  delete_temp_hour: 0
  delete_uploads_hour: 0

filesystem:
  disc_space_warning: 10 # GiB
  db_backup:
    path: /mnt/glados-backup
    is_mount: True

items:
  bought:
    validation:
      project: "^(^[P][0-9]{5}?$|MyExceptionOne|MyException2){1}$"
      product: "^(^[M][0-9]{5}?$|){1}$"
    status:
      open: "open"
      requested: "requested"
      ordered: "ordered"
      late: "late"
      partial: "partial"
      delivered: "delivered"
      canceled: "canceled"
      lost: "lost"
    units:
      default: "PCS"
      values: ["PCS", "M2", "M3"]
    order_by:
      high_priority: "high_priority"
      created: "created"
      project: "project"
      product: "productNumber"
      group_1: "group1"
      manufacturer: "manufacturer"
      supplier: "supplier"

excel:
  header_row: 0
  data_row: 1
  style:
    font: "Monospac821 BT"
    size: 8
    header_color: "FFFFFF"
    header_bg_color: "007ACC"
    data_color_1: "000000"
    data_bg_color_1: "F0F0F0"
    data_color_2: "000000"
    data_bg_color_2: "FFFFFF"

mailing:
  server: smtp.office365.com
  port: 587
  account: glados@company.com
  password: "FooBarBla"
  debug_receiver: admin@company.com
  debug_no_send: True

templates:
  bought_item_excel_import: "bought_item_import.xlsx"
  mail_item_notification: "item_notification.j2"
  mail_schedule_error: "schedule_error.j2"
  mail_disc_space_warning: "disc_space_warning.j2"
  mail_welcome: "welcome.j2"

init:
  full_name: "System"
  mail: glados@company.com
  password: "12345678"
