"""add theme

Revision ID: 1ffaf22f524c
Revises: ed7ee21cc61e
Create Date: 2024-11-19 08:40:31.620622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1ffaf22f524c"
down_revision = "ed7ee21cc61e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_table", schema=None) as batch_op:
        batch_op.add_column(sa.Column("theme", sa.String(), server_default="dark", nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_table", schema=None) as batch_op:
        batch_op.drop_column("theme")

    # ### end Alembic commands ###
