"""add break by day

Revision ID: 44bf23b4a684
Revises: 8723510377cf
Create Date: 2025-06-08 10:42:42.077435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "44bf23b4a684"
down_revision = "8723510377cf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_table", schema=None) as batch_op:
        batch_op.add_column(sa.Column("auto_break_mon", sa.Boolean(), server_default=sa.text("1"), nullable=False))
        batch_op.add_column(sa.Column("auto_break_tue", sa.Boolean(), server_default=sa.text("1"), nullable=False))
        batch_op.add_column(sa.Column("auto_break_wed", sa.Boolean(), server_default=sa.text("1"), nullable=False))
        batch_op.add_column(sa.Column("auto_break_thu", sa.Boolean(), server_default=sa.text("1"), nullable=False))
        batch_op.add_column(sa.Column("auto_break_fri", sa.Boolean(), server_default=sa.text("1"), nullable=False))
        batch_op.add_column(sa.Column("auto_break_sat", sa.Boolean(), server_default=sa.text("1"), nullable=False))
        batch_op.add_column(sa.Column("auto_break_sun", sa.Boolean(), server_default=sa.text("1"), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_table", schema=None) as batch_op:
        batch_op.drop_column("auto_break_sun")
        batch_op.drop_column("auto_break_sat")
        batch_op.drop_column("auto_break_fri")
        batch_op.drop_column("auto_break_thu")
        batch_op.drop_column("auto_break_wed")
        batch_op.drop_column("auto_break_tue")
        batch_op.drop_column("auto_break_mon")

    # ### end Alembic commands ###
