"""add_user_time_table

Revision ID: 8723510377cf
Revises: b8e97eca009f
Create Date: 2025-02-13 10:13:27.394990

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8723510377cf"
down_revision = "b8e97eca009f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_time_table",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("login", sa.DateTime(), nullable=True),
        sa.Column("logout", sa.DateTime(), nullable=True),
        sa.Column("duration_minutes", sa.Float(), nullable=True),
        sa.Column("note", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user_table.id"], name="fk_user_time_table_user_id_user_table"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user_time_table", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_time_table_id"), ["id"], unique=True)

    with op.batch_alter_table("user_table", schema=None) as batch_op:
        batch_op.add_column(sa.Column("work_hours_per_week", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("auto_break_from", sa.Time(), nullable=True))
        batch_op.add_column(sa.Column("auto_break_to", sa.Time(), nullable=True))
        batch_op.add_column(sa.Column("auto_logout", sa.Boolean(), server_default=sa.text("1"), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_table", schema=None) as batch_op:
        batch_op.drop_column("auto_logout")
        batch_op.drop_column("auto_break_to")
        batch_op.drop_column("auto_break_from")
        batch_op.drop_column("work_hours_per_week")

    with op.batch_alter_table("user_time_table", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_time_table_id"))

    op.drop_table("user_time_table")
    # ### end Alembic commands ###
