"""add rfid

Revision ID: b8e97eca009f
Revises: 1ffaf22f524c
Create Date: 2024-12-01 16:41:59.287185

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "b8e97eca009f"
down_revision = "1ffaf22f524c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_table", schema=None) as batch_op:
        batch_op.add_column(sa.Column("hashed_rfid", sa.String(), nullable=True))
        batch_op.create_unique_constraint("uc_user_table_hashed_rfid", ["hashed_rfid"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_table", schema=None) as batch_op:
        batch_op.drop_constraint("uc_user_table_hashed_rfid", type_="unique")
        batch_op.drop_column("hashed_rfid")

    # ### end Alembic commands ###
