"""add language

Revision ID: ed7ee21cc61e
Revises: 824d657001b8
Create Date: 2024-11-16 15:58:42.527701

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "ed7ee21cc61e"
down_revision = "824d657001b8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_table", schema=None) as batch_op:
        batch_op.add_column(sa.Column("language", sa.String(), server_default="enGB", nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_table", schema=None) as batch_op:
        batch_op.drop_column("language")

    # ### end Alembic commands ###
